apiVersion: skaffold/v2beta10
kind: Config

profiles:
- name: mongo-dev
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/dev/mongo-sc.yaml
        - ./k8s-spec/dev/mongo-pvc.yaml
        - ./k8s-spec/dev/mongo-dep.yaml

- name: ingress-dev
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/dev/auth-ingress-static.yaml

- name: development
  build:
    artifacts:
    - image: boyroywax/ore-discord-dev
      context: ./bot/
      docker:
        dockerfile: ./Dockerfile
    - image: boyroywax/ore-discord-callback-dev
      context: ./callback/
      docker:
        dockerfile: ./Dockerfile
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/dev/secrets.yaml
        - ./k8s-spec/dev/configmap.yaml
        - ./k8s-spec/dev/discord-bot-dep.yaml
        - ./k8s-spec/dev/discord-callback-dep.yaml

- name: mongo-prod
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/prod/mongo-sc.yaml
        - ./k8s-spec/prod/mongo-pvc.yaml
        - ./k8s-spec/prod/mongo-dep.yaml

- name: ingress-prod
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/prod/auth-ingress.yaml

- name: loadbalance-prod
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/prod/discord-callback-lb.yaml

- name: production
  build:
    artifacts:
    - image: boyroywax/ore-discord-bot
      context: ./bot/
      docker:
        dockerfile: ./Dockerfile
    - image: boyroywax/ore-discord-callback
      context: ./callback/
      docker:
        dockerfile: ./Dockerfile
  deploy:
    kubectl:
      manifests:
        - ./k8s-spec/prod/secrets.yaml
        - ./k8s-spec/prod/configmap.yaml
        - ./k8s-spec/prod/discord-bot-dep.yaml
        - ./k8s-spec/prod/discord-callback-dep.yaml
