apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: ore
  annotations:
    kubernetes.io/ingress.class: "gce"
    # kubernetes.io/ingress.global-static-ip-name: "ore-discord-bot"
spec:
  defaultBackend:
    service:
      name: ore-callback-p
      port:
        name: http
  # rules:
  # - host: "cb.ore.network"
  #   http:
  #     paths:
  #     - pathType: Prefix
  #       path: "/"
  #       backend:
  #         service:
  #           name: ore-callback-p
  #           port:
  #             name: http
