apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-ingress
  namespace: ore
  annotations:
    kubernetes.io/ingress.class: "gce"
# spec:
#   rules:
#   - host: cb.ore.network
#     http:
#       paths:
#       - pathType: ImplementationSpecific
#         path: "/*"
#         backend:
#           service:
#             name: ore-callback-p
#             port:
#               name: http
spec:
  defaultBackend:
    service:
      name: ore-callback-p
      port:
        name: http