apiVersion: apps/v1
kind: Production
metadata:
  name: discord-service
  namespace: ore
  labels:
    app: discord-service
    tier: backend
    env: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-service
      tier: backend
      env: production
  template:
    metadata:
      labels:
        app: discord-service
        tier: backend
        env: production
    spec:
      containers:
      - name: ore-discord-service
        image: boyroywax/ore-discord-service
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        envFrom:
          - configMapRef:
              name: config
          - secretRef:
              name: bot-secrets
        ports:
        - containerPort: 53134
          name: ore-service-p
        securityContext:
          runAsUser: 1000
          runAsNonRoot: true
        startupProbe:
          httpGet:
            path: /liveness-check
            port: 53134
          failureThreshold: 10
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health-check
            port: 53134
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /liveness-check
            port: 53134
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 2
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ore-service-p
  namespace: ore
spec:
  type: NodePort
  ports:
    - port: 53134
      protocol: TCP
      targetPort: 53134
      name: http
  selector:
    app: discord-service
    tier: backend
    env: production
---
