apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ore-pvc-mongo
  namespace: ore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: mongo-sc
