---
apiVersion: v1
kind: Service
metadata:
  name: ore-callback-d
  namespace: ore-dev
spec:
  type: LoadBalancer
  ports:
    - port: 53134
      protocol: TCP
      targetPort: 53134
      name: http
  selector:
    app: discord-callback
    tier: backend
    env: development
---