---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-dev
  namespace: ore-dev
data:
  # General
  STAGE: Development
  VERSION: Beta v0.0.9

  # Bot Options
  BOT_ADMIN_MODE: "true"
  BOT_ACTIVITY_LOG_MAX: "10"
  BOT_FAUCET_USER: "000000000000000099"
  BOT_FAUCET_TIME_lIMIT: "18000000" # (3hrs x 60min x 60sec x 1000msec)
  BOT_FAUCET_MIN: "0.01"
  BOT_FAUCET_MAX: "0.10"
  BOT_TREASURER_OWNER_PUB_KEY: EOS5dNG4Ei7Ci2Upz85dz4TenUQR747LDobYAQyUrkKF7dxGD1ov8
  BOT_TREASURER_ACTIVE_PUB_KEY: EOS6CsupYZsXpfambQ4ZW194CcwRKk8k15Zsye9oFjNHEHUEaptHm
  BOT_TREASURER_OREID: ore1sqvihyhs

  # CoinGecko API
  COINGECKO_API_ENDPOINT: https://api.coingecko.com
  COINGECKO_API_ID: ptokens-ore
  COINGECKO_LOGO: https://static.coingecko.com/s/thumbnail-007177f3eca19695592f0b8b0eabbdae282b54154e1be912285c9034ea6cbaf2.png

  # CoinMarketCap API
  CMC_EMAIL: james@aikon.com
  CMC_API_ENDPOINT: https://pro-api.coinmarketcap.com
  CMC_API_RESET_TIME: "260000" # (260sec x 1000msec)

  # Currency Info
  CURRENCY: ORE
  CURRENCY_NAME: Open Rights Exchange
  CURRENCY_TOKEN: ORE
  CURRENCY_PRECISION: "8"
  CURRENCY_ACCOUNT: eosio.token
  CURRENCY_BLOCK_EXPLORER: https://explorer.staging.ore.network/
  CURRENCY_LOGO: https://imgur.com/5M8hB6N.png
  CURRENCY_STAGE: testnet  # mainnet or testnet
  CURRENCY_MAINNET: https://ore.openrights.exchange
  CURRENCY_TESTNET: https://ore-staging.openrights.exchange

  # Discord
  DISCORD_CLIENT_ID: "945759694411157544"
  DISCORD_GUILD_ID: "945764140520189952"
  DISCORD_INVITE_URL: https://discord.gg/82J9UYy7z7
  DISCORD_CHANNEL: https://discord.com/channels/945764140520189952/945764180227682334

  # MongoDB
  MONGO_HOST: ore-mongo-dev
  MONGO_PORT: "27017"
  MONGO_URI: mongodb://ore-mongo-dev:27017/test?retryWrites=true&w=majority

  # ORE-ID
  OREID_APP_ID: t_fb2b26c75d5345b28228fba1ff45b6f7
  OREID_APP_NAME: ORE Network Bot
  OREID_URL: https://service.oreid.io
  OREID_AUTH_CALLBACK_URL: http://34.102.183.104/auth
  OREID_LOGOUT_CALLBACK_URL: http://34.102.183.104/logout
  OREID_SIGN_CALLBACK_URL: http://34.102.183.104/sign
  OREID_CALLBACK_PORT: "53134"
  OREID_LOGO: https://i.imgur.com/A3yS9pl.png
  OREID_HOME: https://oreid.io
  ORE_MAINNET_APPOREID_PUB_KEY: EOS5aYG86TMML4FKaQDwCrehykivpga7V9fPNRCzU2oHsQNkbTiNG
  ORE_TESTNET_APPOREID_PUB_KEY: EOS7rNR9AhgcqkmMAoUSHrjTXgxM4PnpGYDXhS3B4UW3jjZgBATXL
