apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-callback
  namespace: ore-dev
  labels:
    app: discord-callback
    tier: frontend
    env: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord-callback
      tier: frontend
      env: development
  template:
    metadata:
      labels:
        app: discord-callback
        tier: frontend
        env: development
    spec:
      containers:
      - name: ore-discord-callback-dev
        image: boyroywax/ore-discord-callback-dev
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "100m"
        # envFrom:
        #   - configMapRef:
        #       name: config-dev
        #   - secretRef:
        #       name: bot-secrets-dev
        # env:
        #   - name: REACT_APP_OREID_APP_ID
        #     valueFrom:
        #       configMapKeyRef:
        #         name: config-dev
        #         key: OREID_APP_ID 
        ports:
        - containerPort: 3000
          name: ore-callback-d
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ore-callback-d
  namespace: ore-dev
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http
  selector:
    app: discord-callback
    tier: frontend
    env: development
---
