apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ore-pvc-mongo-dev
  namespace: ore-dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: mongo-sc-dev
