apiVersion: v1
kind: Secret
metadata:
  name: bot-secrets-dev
  namespace: ore-dev
type: Opaque
data:
  BOT_SECRET: base64EncodedString
  DISCORD_TOKEN: base64EncodedString
  SENTRY_DSN: base64EncodedString
  OREID_API_KEY: base64EncodedString